<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MasLazu.AspNet.Authentication.Core.Abstraction" />
    <PackageReference Include="MasLazu.AspNet.Framework.Application" />
    <PackageReference Include="MasLazu.AspNet.Verification.Abstraction" />
    <PackageReference Include="BCrypt.Net-Next" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MasLazu.AspNet.Authentication.Password.Abstraction\MasLazu.AspNet.Authentication.Password.Abstraction.csproj" />
    <ProjectReference Include="..\MasLazu.AspNet.Authentication.Password.Domain\MasLazu.AspNet.Authentication.Password.Domain.csproj" />
  </ItemGroup>

</Project>
