<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <!-- MasLazu Framework Packages -->
    <PackageVersion Include="MasLazu.AspNet.Framework.Application" Version="1.0.0-preview.12" />
    <PackageVersion Include="MasLazu.AspNet.Framework.Domain" Version="1.0.0-preview.12" />
    <PackageVersion Include="MasLazu.AspNet.Framework.EfCore" Version="1.0.0-preview.12" />
    <PackageVersion Include="MasLazu.AspNet.Framework.Endpoint" Version="1.0.0-preview.12" />

    <!-- Authentication Packages -->
    <PackageVersion Include="MasLazu.AspNet.Authentication.Core.Abstraction" Version="1.0.0-preview.7" />
    <PackageVersion Include="MasLazu.AspNet.Verification.Abstraction" Version="1.0.0-preview.5" />

    <!-- Microsoft Packages -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />

    <!-- Third-party Packages -->
    <PackageVersion Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageVersion Include="FastEndpoints" Version="7.0.1" />
  </ItemGroup>
</Project>