<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MasLazu.AspNet.Framework.EfCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MasLazu.AspNet.Authentication.Password.Domain\MasLazu.AspNet.Authentication.Password.Domain.csproj" />
  </ItemGroup>

</Project>
